# Generated by Django 4.0.1 on 2022-01-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
