# Generated by Django 4.0.1 on 2022-02-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0006_remove_students_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='confirm_password',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
